//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LottoRunner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LottoRunner.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are your ready to play? {0}.
        /// </summary>
        internal static string AreYouReady {
            get {
                return ResourceManager.GetString("AreYouReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to pick your own numbers, or have them choosen for you? {0}.
        /// </summary>
        internal static string DrawBallQuestion {
            get {
                return ResourceManager.GetString("DrawBallQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your numbers, seperated by space. Remember, the min white is {0}, max white is {1}, min red is {2}, max red is {3}.
        /// </summary>
        internal static string EnterYourBalls {
            get {
                return ResourceManager.GetString("EnterYourBalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not the right number of numbers entered.
        /// </summary>
        internal static string ErrorBadUserInput {
            get {
                return ResourceManager.GetString("ErrorBadUserInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        internal static string NoOneLetterLower {
            get {
                return ResourceManager.GetString("NoOneLetterLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs so far:\t{0}\t last offical ball set: {1}.
        /// </summary>
        internal static string RunsAndBallSet {
            get {
                return ResourceManager.GetString("RunsAndBallSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs before victory: {0}.
        /// </summary>
        internal static string TotalRuns {
            get {
                return ResourceManager.GetString("TotalRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the lotto! good luck :p .
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string YesOneLetterLower {
            get {
                return ResourceManager.GetString("YesOneLetterLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}/{1}).
        /// </summary>
        internal static string YesOrNo {
            get {
                return ResourceManager.GetString("YesOrNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your numbers are {0}.
        /// </summary>
        internal static string YourNumbers {
            get {
                return ResourceManager.GetString("YourNumbers", resourceCulture);
            }
        }
    }
}
